### ISSUE TITLE
[HTDA01][C#][API] Chức năng cập nhật merchant

### ISSUE THREAD

**Issue by thuthoi** [thuthoi/ptudhttthd#15]
[HTDA01][C#] Chức năng cập nhật merchant

**Comment by htnhan93** [comment]
T không start service được nên chưa test hàm được.
Bà Thu hay ai đó test hàm dùm t nha.
Để t coi lại vụ start service

**Comment by thuthoi** [comment]
Được chưa ông?

**Comment by htnhan93** [comment]
OK rồi bà để t commit lên lại
Nãy test nhầm

**Comment by thuthoi** [comment]
ok

**Comment by thuthoi** [comment]
Set thời gian làm đi ông, chỗ estimate
