### ISSUE TITLE
[HTDA02][ASP.NET] Hoàn chỉnh chức năng cập nhật merchant trên website

### ISSUE THREAD

**Issue by thuthoi** [thuthoi/ptudhttthd#18]
[HTDA02][ASP.NET] Hoàn chỉnh chức năng cập nhật merchant trên website dựa trên api cập nhật merchant

**Comment by htnhan93** [comment]
Thu cho t nợ cái chức năng này nha. Hôm nay làm không kịp. Tuần sau làm bù

**Comment by thuthoi** [comment]
1. Cái update thiếu chỗ chọn status nha(active với inactive á)
2. Với lại cái merchant nào mà ko có agent nào quản lý thì khi nhấn update nó sẽ bung lỗi
