### ISSUE TITLE
[HTDA02][ASP.NET] Thực hiện chức năng Tạo agent trên website

### ISSUE THREAD

**Issue by thuthoi** [thuthoi/ptudhttthd#23]
[HTDA02][ASP.NET] Thực hiện chức năng Tạo agent trên website:
+ Viết API
+ Thiết kế giao diện
+ Gắn API vào giao diện

**Comment by htnhan93** [comment]
Chưa test được mọi người test dùm t nha. Do đang gấp nên không test được
