### ISSUE TITLE
[HTDA03][ASP.NET] Tạo menubar và header cho website

### ISSUE THREAD

**Issue by thuthoi** [thuthoi/ptudhttthd#27]
- Tạo trang master

- Tạo trang index cho merchant, master, agent

- Hiển thị người đăng nhập trên header

**Comment by thuthoi** [comment]
Tester: Thu Phạm

**Comment by thuthoi** [comment]
@hieunguyen1506 Sửa được cái drop down menu trong search chưa ông?

**Comment by hieunguyen1506** [comment]
t đang làm, bla bla ,,,,

**Comment by thuthoi** [comment]
Go to hell!

**Comment by hieunguyen1506** [comment]
đã fix

**Comment by thuthoi** [comment]
@hieunguyen1506 Ông coi cái master page bị gì mà mấy nút bấm không ăn vậy ông, mấy nút được bắt sự kiện bên server side?
