### ISSUE TITLE
[C#][ASP.NET] Báo cáo phân hệ master

### ISSUE THREAD

**Issue by thuthoi** [thuthoi/ptudhttthd#37]
Chức năng "Báo cáo phân hệ master (Daily, Monthly, Quarterly, Yearly, MonthToDate, YearToDate, Sự tương quan, Xuất ra báo biểu ...)"
Thực hiện: Hiếu Nguyễn
Tester: Thu Phạm

**Comment by hieunguyen1506** [comment]
Từ bỏ Sự tương quan....

**Comment by thuthoi** [comment]
Sao bỏ tương quan vậy?

**Comment by hieunguyen1506** [comment]
- Cập nhật 2 chart cho Card
- Sửa DropDownList Master thành TextBox (Label) để không tưởng thành có nhiều Master
